apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: SA-operator
      containers:
        - name: mongodb
          image: mongo
          volumeMounts:
          - name: mongo-persistent
            mountPath: /data/db
          command:
          - mongod 
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent
    spec:
#      storageClassName: manual
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
