apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mynamespace
  labels:
    role: mongo
    environment: test

spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    role: mongo
    environment: test
  type: ClusterIP
