kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-am
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rbd
