apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: Myapp
  name: Myapp
  namespace: Mynamespace
spec:
  ports:
  - name: Myportname
    port: 8080
    targetPort: 8080
  selector:
    app: Myapp
  type: NodePort
