kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gra-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rbd
