apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: redis
  name: redis
  namespace: mynamespace
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
