apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem
