apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: keycloak-claim
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  volumeMode: Filesystem
