 version: '3.3'

services:
  myapp-develop:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "myapp-develop"
## specify your appsettings info
    environment:
      - ASPNETCORE_ENVIRONMENT=develop
networks:
  default:
    external:
      name: develop
