apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: mysql-claim
  namespace: redmine
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeMode: Filesystem
