apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: db
  name: db
  namespace: redmine
spec:
  ports:
  - name: db-redmine
    port: 3306
    targetPort: 3306
  selector:
    app: db
  type: NodePort
