# docker-compose.yml
version: "3"
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - ./nexus-data:/nexus-data
        #      - ./nexus-data-work:/sonatype-work
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
