apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: postwoman
  name: postwoman
  namespace: default
spec:
  ports:
  - name: postwoman
    port: 3000
    targetPort: 3000
  selector:
    app: postwoman
  type: NodePort
