apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: gitlab-postgresql
  name: gitlab-postgresql
  namespace: gitlab
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  selector:
    name: gitlab-postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
