apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gitlab-pvc
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem
