kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-prometheus
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rbd
